### ISSUE TITLE
node-gyp configure error

### ISSUE THREAD

**Issue by Panthr75** [UrielCh/opencv4nodejs#46]
I tried to run node-gyp configure due to it requesting me to do so after building:

# Error Message
```
$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.1.0 | win32 | x64
gyp info find Python using Python version 3.9.13 found at "C:\Users\fluff\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2022 (17.3.32922.545) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\fluff\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\fluff\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\fluff\\VS_Code\\opencv\\test\\node_modules\\@u4\\opencv4nodejs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\fluff\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\fluff\\AppData\\Local\\node-gyp\\Cache\\18.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\fluff\\AppData\\Local\\node-gyp\\Cache\\18.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\fluff\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\fluff\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.1.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\fluff\\VS_Code\\opencv\\test\\node_modules\\@u4\\opencv4nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\fluff\\VS_Code\\opencv\\test\\node_modules\\@u4\\opencv4nodejs\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Call to 'node ./install/parseEnv.js OPENCV4NODEJS_DEFINES' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\fluff\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fluff\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\fluff\VS_Code\opencv\test\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v18.1.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
```

# Auto Build - Full Error Log

Keep in mind the original error message:
```
info defines
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_DNN
info defines OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_FLANN       OPENCV4NODEJS_FOUND_LIBRARY_GAPI        
info defines OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     
info defines OPENCV4NODEJS_FOUND_LIBRARY_ML          OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    
info defines OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install
info install Setting the following includes:
info includes C:/Users/fluff/VS_Code/opencv/test/node_modules/@u4/opencv-build/opencv-4.5.5-ecae4/build/include
info includes C:/Users/fluff/VS_Code/opencv/test/node_modules/@u4/opencv-build/opencv-4.5.5-ecae4/build/include/opencv4
info libs
info libs Setting lib from C:/Users/fluff/VS_Code/opencv/test/node_modules/@u4/opencv-build/opencv-4.5.5-ecae4/build/lib/Release : opencv_calib3d455.lib, opencv_core455.lib, opencv_dnn455.lib, opencv_features2d455.lib, opencv_flann455.lib, opencv_gapi455.lib, opencv_highgui455.lib, opencv_imgcodecs455.lib, opencv_imgproc455.lib, opencv_ml455.lib, opencv_objdetect455.lib, opencv_photo455.lib, opencv_video455.lib, opencv_videoio455.lib, opencv_videostab455.lib, opencv_face455.lib, opencv_text455.lib, opencv_tracking455.lib, opencv_xfeatures2d455.lib, opencv_ximgproc455.lib
info install Spawning in directory:C:\Users\fluff\VS_Code\opencv\test\node_modules\@u4\opencv4nodejs node-gyp process: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.1.0 | win32 | x64
gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (C:\Users\fluff\VS_Code\opencv\test\node_modules\node-gyp\lib\build.js:43:20)
gyp ERR! stack     at ReadFileContext.callback (C:\Users\fluff\VS_Code\opencv\test\node_modules\graceful-fs\graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fluff\\VS_Code\\opencv\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
gyp ERR! cwd C:\Users\fluff\VS_Code\opencv\test\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v18.1.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
error:  Error: Command failed: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.1.0 | win32 | x64
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (C:\Users\fluff\VS_Code\opencv\test\node_modules\node-gyp\lib\build.js:43:20)
gyp ERR! stack     at ReadFileContext.callback (C:\Users\fluff\VS_Code\opencv\test\node_modules\graceful-fs\graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fluff\\VS_Code\\opencv\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
gyp ERR! cwd C:\Users\fluff\VS_Code\opencv\test\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v18.1.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp build --jobs max --release 
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.1.0
ERR! install gyp info using node@18.1.0 | win32 | x64
ERR! install gyp ERR! build error
ERR! install gyp ERR! stack Error: You must run `node-gyp configure` first!
ERR! install gyp ERR! stack     at ReadFileContext.<anonymous> (C:\Users\fluff\VS_Code\opencv\test\node_modules\node-gyp\lib\build.js:43:20)
ERR! install gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
ERR! install gyp ERR! System Windows_NT 10.0.19044
ERR! install gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fluff\\VS_Code\\opencv\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"    
ERR! install gyp ERR! cwd C:\Users\fluff\VS_Code\opencv\test\node_modules\@u4\opencv4nodejs
ERR! install gyp ERR! node -v v18.1.0
ERR! install gyp ERR! node-gyp -v v9.1.0
ERR! install gyp ERR! not ok
ERR! install  return code: 1
```

## Extra Information
I had to hard-code the MS Build directory location because it gave me errors like `Error: EPERM: operation not permitted, lstat 'C:\Config.Msi'`, but this appears to be a library issue, not an issue with this package.

**Comment by UrielCh** [comment]
The issue coming from [tiny-glob](https://www.npmjs.com/package/tiny-glob) package

I had to fork it as [@u4/tiny-glob](https://www.npmjs.com/package/@u4/tiny-glob)

**Comment by UrielCh** [comment]
fixed in 6.2.5

**Comment by UrielCh** [comment]
fixed ?

**Comment by TripShade** [comment]
I have the same issue seems like its not fixed. 
My ~/.zshrc contains.
```zsh
export OPENCV4NODEJS_DISABLE_AUTOBUILD=1
export OPENCV_INCLUDE_DIR=/usr/local/Cellar/opencv/4.6.0_1/include
export OPENCV_LIB_DIR=/usr/local/Cellar/opencv/4.6.0_1/lib
export OPENCV_BIN_DIR=/usr/local/Cellar/opencv/4.6.0_1/bin
```

These are the steps i took leading up to it.
```zsh
nvm use lts/hydrogen

## add library to my project
npm install --save @u4/opencv4nodejs

## run opencv-build once.
./node_modules/.bin/build-opencv --version 4.6.0 --incDir /usr/local/Cellar/opencv/4.6.0_1/include --libDir /usr/local/Cellar/opencv/4.6.0_1/lib --binDir=/usr/local/Cellar/opencv/4.6.0_1/bin rebuild
```
output is the same error as @Panthr75 .


The following may be unrelated but when i remove `export OPENCV4NODEJS_DISABLE_AUTOBUILD=1` then autobuild with.
```zsh
./node_modules/.bin/build-opencv --version 4.6.0 --incDir /usr/local/Cellar/opencv/4.6.0_1/include --libDir /usr/local/Cellar/opencv/4.6.0_1/lib --binDir=/usr/local/Cellar/opencv/4.6.0_1/bin rebuild
```
it gets stuck at 46%

on lower version.
```zsh
./node_modules/.bin/build-opencv --version 4.5.5 --incDir /usr/local/Cellar/opencv/4.6.0_1/include --libDir /usr/local/Cellar/opencv/4.6.0_1/lib --binDir=/usr/local/Cellar/opencv/4.6.0_1/bin rebuild
```

it gets stuck on 73%.

**Comment by ForesightImaging** [comment]
Seems like I'm in the same boat. 
```
PS C:\gitlab\opencv-electron> npm run do-install        
> opencv-electron@1.0.0 do-install
> build-opencv build

info config no opencv4nodejs section found in C:\gitlab\opencv-electron\package.json
info config no opencv4nodejs section found in C:\gitlab\opencv-electron\package.json
info config no opencv4nodejs section found in C:\gitlab\opencv-electron\package.json
info init using openCV verison 4.6.0
info init INIT_CWD is defined overwriting root path to C:\gitlab\opencv-electron
info init Workdir will be: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4
info install Using openCV 4.6.0
info install Using lib dir: C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/lib/Release
info install if you want to use an own OpenCV build set OPENCV4NODEJS_DISABLE_AUTOBUILD to 1, and fill OPENCV_BIN_DIR, OPENCV_INCLUDE_DIR, OPENCV_LIB_DIR environement variables
info install found previous build summery auto-build.json: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\auto-build.json
info install checking for opencv libraries
info install lib calib3d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_calib3d460.lib
info install lib core: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_core460.lib
info install lib dnn: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_dnn460.lib
info install lib features2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_features2d460.lib
info install lib flann: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_flann460.lib
info install lib gapi: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_gapi460.lib
info install lib highgui: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_highgui460.lib
info install lib imgcodecs: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgcodecs460.lib
info install lib imgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgproc460.lib
info install lib ml: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ml460.lib
info install lib objdetect: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_objdetect460.lib
info install lib photo: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_photo460.lib
info install python_tests: ignored
info install lib video: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_video460.lib
info install lib videoio: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videoio460.lib
info install lib videostab: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videostab460.lib
info install lib face: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_face460.lib
info install lib text: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_text460.lib
info install lib tracking: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_tracking460.lib
info install lib xfeatures2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_xfeatures2d460.lib
info install lib ximgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ximgproc460.lib
info install all libraries are installed in C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release => Skip building
info install 
info install Found the following libs:
info install calib3d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_calib3d460.lib
info install core: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_core460.lib
info install dnn: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_dnn460.lib
info install features2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_features2d460.lib
info install flann: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_flann460.lib
info install gapi: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_gapi460.lib
info install highgui: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_highgui460.lib
info install imgcodecs: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgcodecs460.lib
info install imgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgproc460.lib
info install ml: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ml460.lib
info install objdetect: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_objdetect460.lib
info install photo: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_photo460.lib
info install video: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_video460.lib
info install videoio: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videoio460.lib
info install videostab: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videostab460.lib
info install face: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_face460.lib
info install text: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_text460.lib
info install tracking: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_tracking460.lib
info install xfeatures2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_xfeatures2d460.lib
info install ximgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ximgproc460.lib
info defines
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_DNN
info defines OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_FLANN       OPENCV4NODEJS_FOUND_LIBRARY_GAPI        
info defines OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     
info defines OPENCV4NODEJS_FOUND_LIBRARY_ML          OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    
info defines OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install
info install Setting the following includes:
info includes C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/include
info includes C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/include/opencv4
info libs
info libs Setting lib from C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/lib/Release : opencv_calib3d460.lib, opencv_core460.lib, opencv_dnn460.lib, opencv_features2d460.lib, opencv_flann460.lib, opencv_gapi460.lib, opencv_highgui460.lib, opencv_imgcodecs460.lib, opencv_imgproc460.lib, opencv_ml460.lib, opencv_objdetect460.lib, opencv_photo460.lib, opencv_video460.lib, opencv_videoio460.lib, opencv_videostab460.lib, opencv_face460.lib, opencv_text460.lib, opencv_tracking460.lib, opencv_xfeatures2d460.lib, opencv_ximgproc460.lib
info install Spawning in directory:C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs node-gyp process: node-gyp build --jobs max --release
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | win32 | x64
gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (C:\gitlab\opencv-electron\node_modules\node-gyp\lib\build.js:45:20)
gyp ERR! stack     at ReadFileContext.callback (C:\gitlab\opencv-electron\node_modules\graceful-fs\graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\gitlab\\opencv-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
gyp ERR! cwd C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
error:  Error: Command failed: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | win32 | x64
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (C:\gitlab\opencv-electron\node_modules\node-gyp\lib\build.js:45:20)
gyp ERR! stack     at ReadFileContext.callback (C:\gitlab\opencv-electron\node_modules\graceful-fs\graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\gitlab\\opencv-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
gyp ERR! cwd C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp build --jobs max --release
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.3.1
ERR! install gyp info using node@16.19.0 | win32 | x64
ERR! install gyp ERR! build error
ERR! install gyp ERR! stack Error: You must run `node-gyp configure` first!
ERR! install gyp ERR! stack     at ReadFileContext.<anonymous> (C:\gitlab\opencv-electron\node_modules\node-gyp\lib\build.js:45:20)
ERR! install gyp ERR! stack     at ReadFileContext.callback (C:\gitlab\opencv-electron\node_modules\graceful-fs\graceful-fs.js:123:16)
ERR! install gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
ERR! install gyp ERR! System Windows_NT 10.0.19045
ERR! install gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\gitlab\\opencv-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs
ERR! install gyp ERR! node -v v16.19.0
ERR! install gyp ERR! node-gyp -v v9.3.1
ERR! install gyp ERR! not ok
ERR! install  return code: 1
```

**Comment by ForesightImaging** [comment]
I attempted to resolve this by running node-gyp configure in node_modules\@u4\opencv4nodejs
```
PS C:\gitlab\opencv-electron> cd node_modules\@u4\opencv4nodejs
PS C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs> node-gyp configure
gyp info it worked if it ends with ok    
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | win32 | x64
gyp info find Python using Python version 3.10.5 found at "C:\Python310\python.exe"
gyp info find VS using VS2022 (17.3.32929.385) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\stroppoli\\AppData\\Roaming\\nvm\\v16.19.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\gitlab\\opencv-electron\\node_modules\\@u4\\opencv4nodejs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\stroppoli\\AppData\\Roaming\\nvm\\v16.19.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\stroppoli\\AppData\\Local\\node-gyp\\Cache\\16.19.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\stroppoli\\AppData\\Local\\node-gyp\\Cache\\16.19.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\stroppoli\\AppData\\Roaming\\nvm\\v16.19.0\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\stroppoli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.19.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\gitlab\\opencv-electron\\node_modules\\@u4\\opencv4nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\gitlab\\opencv-electron\\node_modules\\@u4\\opencv4nodejs\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
PS C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs>
```

After this I re-ran the build and the results were different, It's loogin for a file that isn't there 'opencv2/core.hpp' 

```
> opencv-electron@1.0.0 do-install
> build-opencv build

info config no opencv4nodejs section found in C:\gitlab\opencv-electron\package.json
info config no opencv4nodejs section found in C:\gitlab\opencv-electron\package.json
info config no opencv4nodejs section found in C:\gitlab\opencv-electron\package.json
info init using openCV verison 4.6.0
info init INIT_CWD is defined overwriting root path to C:\gitlab\opencv-electron
info init Workdir will be: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4
info install Using openCV 4.6.0
info install Using lib dir: C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/lib/Release
info install if you want to use an own OpenCV build set OPENCV4NODEJS_DISABLE_AUTOBUILD to 1, and fill OPENCV_BIN_DIR, OPENCV_INCLUDE_DIR, OPENCV_LIB_DIR environement variables
info install found previous build summery auto-build.json: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\auto-build.json
info install checking for opencv libraries
info install lib calib3d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_calib3d460.lib
info install lib core: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_core460.lib
info install lib dnn: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_dnn460.lib
info install lib features2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_features2d460.lib
info install lib flann: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_flann460.lib
info install lib gapi: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_gapi460.lib
info install lib highgui: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_highgui460.lib
info install lib imgcodecs: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgcodecs460.lib
info install lib imgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgproc460.lib
info install lib ml: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ml460.lib
info install lib objdetect: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_objdetect460.lib
info install lib photo: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_photo460.lib
info install python_tests: ignored
info install lib video: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_video460.lib
info install lib videoio: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videoio460.lib
info install lib videostab: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videostab460.lib
info install lib face: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_face460.lib
info install lib text: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_text460.lib
info install lib tracking: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_tracking460.lib
info install lib xfeatures2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_xfeatures2d460.lib
info install lib ximgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ximgproc460.lib
info install all libraries are installed in C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release => Skip building
info install
info install Found the following libs:
info install calib3d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_calib3d460.lib
info install core: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_core460.lib
info install dnn: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_dnn460.lib
info install features2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_features2d460.lib
info install flann: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_flann460.lib
info install gapi: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_gapi460.lib
info install highgui: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_highgui460.lib
info install imgcodecs: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgcodecs460.lib
info install imgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_imgproc460.lib
info install ml: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ml460.lib
info install objdetect: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_objdetect460.lib
info install photo: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_photo460.lib
info install video: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_video460.lib
info install videoio: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videoio460.lib
info install videostab: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_videostab460.lib
info install face: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_face460.lib
info install text: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_text460.lib
info install tracking: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_tracking460.lib
info install xfeatures2d: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_xfeatures2d460.lib
info install ximgproc: C:\gitlab\opencv-electron\node_modules\@u4\opencv-build\dist\opencv-4.6.0-ecae4\build\lib\Release\opencv_ximgproc460.lib
info defines
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_DNN
info defines OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_FLANN       OPENCV4NODEJS_FOUND_LIBRARY_GAPI        
info defines OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     
info defines OPENCV4NODEJS_FOUND_LIBRARY_ML          OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    
info defines OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install
info install Setting the following includes:
info includes C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/include
info includes C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/include/opencv4
info libs
info libs Setting lib from C:/gitlab/opencv-electron/node_modules/@u4/opencv-build/dist/opencv-4.6.0-ecae4/build/lib/Release : opencv_calib3d460.lib, opencv_core460.lib, opencv_dnn460.lib, opencv_features2d460.lib, opencv_flann460.lib, opencv_gapi460.lib, opencv_highgui460.lib, opencv_imgcodecs460.lib, opencv_imgproc460.lib, opencv_ml460.lib, 
opencv_objdetect460.lib, opencv_photo460.lib, opencv_video460.lib, opencv_videoio460.lib, opencv_videostab460.lib, opencv_face460.lib, opencv_text460.lib, opencv_tracking460.lib, opencv_xfeatures2d460.lib, opencv_ximgproc460.lib
info install Spawning in directory:C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs node-gyp process: node-gyp build --jobs max --release
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | win32 | x64
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   '/m:16'
gyp info spawn args ]
  opencv4nodejs.cc
C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs\cc\macros.h(2,10): fatal  error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory [C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs\build\opencv4nodejs.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\gitlab\opencv-electron\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\gitlab\\opencv-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
gyp ERR! cwd C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
error:  Error: Command failed: node-gyp build --jobs max --release
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | win32 | x64
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   '/m:16'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\gitlab\opencv-electron\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\gitlab\\opencv-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
gyp ERR! cwd C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp build --jobs max --release
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.3.1
ERR! install gyp info using node@16.19.0 | win32 | x64
ERR! install gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
ERR! install gyp info spawn args [
ERR! install gyp info spawn args   'build/binding.sln',
ERR! install gyp info spawn args   '/clp:Verbosity=minimal',
ERR! install gyp info spawn args   '/nologo',
ERR! install gyp info spawn args   '/p:Configuration=Release;Platform=x64',
ERR! install gyp info spawn args   '/m:16'
ERR! install gyp info spawn args ]
ERR! install gyp ERR! build error
ERR! install gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
ERR! install gyp ERR! stack     at ChildProcess.onExit (C:\gitlab\opencv-electron\node_modules\node-gyp\lib\build.js:203:23)
ERR! install gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
ERR! install gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
ERR! install gyp ERR! System Windows_NT 10.0.19045
ERR! install gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\gitlab\\opencv-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd C:\gitlab\opencv-electron\node_modules\@u4\opencv4nodejs
ERR! install gyp ERR! node -v v16.19.0
ERR! install gyp ERR! node-gyp -v v9.3.1
ERR! install gyp ERR! not ok
ERR! install  return code: 1
PS C:\gitlab\opencv-electron>
```

**Comment by UrielCh** [comment]
fix your "do-install" task from
`build-opencv build`
to
`build-opencv --electron build`
but first run
`build-opencv --electron rebuild`

**Comment by UrielCh** [comment]
If there you see some misleading command int the doc, tell me where, I will fix them.
